### PR TITLE
Manage Mindvalley's Github using Terrafrom

### PR DESCRIPTION
**Pull request by zacaaron**

### CODE REVIEW

**Comment by naiduarvind** [comment]
atlantis plan

**Comment by sauron-droid** [comment]
Ran Plan for dir: `github` workspace: `default`

**Plan Error**
```
running "/home/atlantis/.atlantis/bin/terraform0.12.0 plan -input=false -refresh -no-color -out \"/home/atlantis/.atlantis/repos/mindvalley/auxiliary/6/default/github/github-collaborator-provisioning-default.tfplan\"" in "/home/atlantis/.atlantis/repos/mindvalley/auxiliary/6/default/github": exit status 1

Error: Unassigned variable

The input variable "github_token" has not been assigned a value. This is a bug
in Terraform; please report it in a GitHub issue.


```

**Comment by sauron-droid** [comment]
Ran Plan for dir: `github` workspace: `default`

**Plan Error**
```
exit status 127: running "my-custom-command arg1 arg2" in "/home/atlantis/.atlantis/repos/mindvalley/auxiliary/6/default/github": 
sh: my-custom-command: not found


```

**Comment by sauron-droid** [comment]
Ran Plan for dir: `github` workspace: `default`

**Plan Error**
```
exit status 127: running "my-custom-command arg1 arg2" in "/home/atlantis/.atlantis/repos/mindvalley/auxiliary/6/default/github": 
sh: my-custom-command: not found


```

**Comment by sauron-droid** [comment]
Ran Plan for dir: `github` workspace: `default`

**Plan Error**
```
exit status 127: running "my-custom-command arg1 arg2" in "/home/atlantis/.atlantis/repos/mindvalley/auxiliary/6/default/github": 
sh: my-custom-command: not found


```

**Comment by sauron-droid** [comment]
Ran Plan for dir: `github` workspace: `default`

**Plan Error**
```
exit status 127: running "my-custom-command arg1 arg2" in "/home/atlantis/.atlantis/repos/mindvalley/auxiliary/6/default/github": 
sh: my-custom-command: not found


```

**Comment by sauron-droid** [comment]
Ran Plan for dir: `github` workspace: `default`

**Plan Error**
```
exit status 127: running "my-custom-command arg1 arg2" in "/home/atlantis/.atlantis/repos/mindvalley/auxiliary/6/default/github": 
sh: my-custom-command: not found


```

**Comment by sauron-droid** [comment]
Ran Plan for dir: `github` workspace: `default`

**Plan Error**
```
exit status 127: running "my-custom-command arg1 arg2" in "/home/atlantis/.atlantis/repos/mindvalley/auxiliary/6/default/github": 
sh: my-custom-command: not found


```

**Comment by sauron-droid** [comment]
Ran Plan for dir: `github` workspace: `default`

**Plan Error**
```
exit status 127: running "my-custom-command arg1 arg2" in "/home/atlantis/.atlantis/repos/mindvalley/auxiliary/6/default/github": 
sh: my-custom-command: not found


```

**Comment by sauron-droid** [comment]
Ran Plan for dir: `github` workspace: `default`

**Plan Error**
```
exit status 127: running "my-custom-command arg1 arg2" in "/home/atlantis/.atlantis/repos/mindvalley/auxiliary/6/default/github": 
sh: my-custom-command: not found


```

**Comment by sauron-droid** [comment]
Ran Plan for dir: `github` workspace: `default`

**Plan Error**
```
exit status 127: running "my-custom-command arg1 arg2" in "/home/atlantis/.atlantis/repos/mindvalley/auxiliary/6/default/github": 
sh: my-custom-command: not found


```

**Comment by naiduarvind** [comment]
atlantis plan -d github/modules/organizations/members

**Comment by sauron-droid** [comment]
Ran Plan for dir: `github/modules/organizations/members` workspace: `default`

**Plan Error**
```
dir "github/modules/organizations/members" does not exist
```

**Comment by naiduarvind** [comment]
atlantis plan -d github/modules/organization/members

**Comment by sauron-droid** [comment]
Ran Plan for dir: `github/modules/organization/members` workspace: `default`

**Plan Error**
```
running "/usr/local/bin/terraform plan -input=false -refresh -no-color -out \"/home/atlantis/.atlantis/repos/mindvalley/auxiliary/6/default/github/modules/organization/members/default.tfplan\"" in "/home/atlantis/.atlantis/repos/mindvalley/auxiliary/6/default/github/modules/organization/members": exit status 1
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.


Error: If `anonymous` is false, `token` is required.

  on ../../../versions.tf line 5, in provider "github":
   5: provider "github" {



```

**Comment by naiduarvind** [comment]
atlantis plan -d github/modules/organization/members

**Comment by sauron-droid** [comment]
Ran Plan for dir: `github/modules/organization/members` workspace: `default`

**Plan Error**
<details><summary>Show Output</summary>

```
running "/usr/local/bin/terraform plan -input=false -refresh -no-color -out \"/home/atlantis/.atlantis/repos/mindvalley/auxiliary/6/default/github/modules/organization/members/default.tfplan\"" in "/home/atlantis/.atlantis/repos/mindvalley/auxiliary/6/default/github/modules/organization/members": exit status 1
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

module.leylmordor.data.github_team.organization-teams: Refreshing state...

Error: Get https://api.github.com/orgs/mindvalley/teams?per_page=10: net/http: invalid header field value "Bearer da91d9f3a3e8c4e05920a8b2e76bd97fefa7a800\n" for key Authorization

  on ../../../main.tf line 14, in data "github_team" "organization-teams":
  14: data "github_team" "organization-teams" {



```
</details>

**Comment by naiduarvind** [comment]
atlantis plan -d github/modules/organization/members

**Comment by sauron-droid** [comment]
Ran Plan for dir: `github/modules/organization/members` workspace: `default`

<details><summary>Show Output</summary>

```diff

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
+ create

Terraform will perform the following actions:

  # module.leylmordor.github_membership.organization-membership will be created
+ resource "github_membership" "organization-membership" {
      + etag     = (known after apply)
      + id       = (known after apply)
      + role     = "admin"
      + username = "leylmordor"
    }

  # module.leylmordor.github_team_membership.team-membership will be created
+ resource "github_team_membership" "team-membership" {
      + etag     = (known after apply)
      + id       = (known after apply)
      + role     = "member"
      + team_id  = "3115450"
      + username = "leylmordor"
    }

Plan: 2 to add, 0 to change, 0 to destroy.

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d github/modules/organization/members`
* :put_litter_in_its_place: To **delete** this plan click [here](http://atlantis-595cd8b7bc-wdzjk:4141/lock?id=mindvalley%252Fauxiliary%252Fgithub%252Fmodules%252Forganization%252Fmembers%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d github/modules/organization/members`
</details>

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`

**Comment by naiduarvind** [comment]
atlantis apply

**Comment by sauron-droid** [comment]
**Apply Error**
```
stat /home/atlantis/.atlantis/repos/mindvalley/auxiliary/6: no such file or directory
```

**Comment by naiduarvind** [comment]
atlantis apply -d github/modules/organization/members

**Comment by sauron-droid** [comment]
**Apply Error**
```
checking if workspace exists: stat /home/atlantis/.atlantis/repos/mindvalley/auxiliary/6/default: no such file or directory
```

**Comment by naiduarvind** [comment]
atlantis plan -d github/modules/organization/members

**Comment by sauron-droid** [comment]
Ran Plan for dir: `github/modules/organization/members` workspace: `default`

<details><summary>Show Output</summary>

```diff

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
+ create

Terraform will perform the following actions:

  # module.leylmordor.github_membership.organization-membership will be created
+ resource "github_membership" "organization-membership" {
      + etag     = (known after apply)
      + id       = (known after apply)
      + role     = "admin"
      + username = "leylmordor"
    }

  # module.leylmordor.github_team_membership.team-membership will be created
+ resource "github_team_membership" "team-membership" {
      + etag     = (known after apply)
      + id       = (known after apply)
      + role     = "member"
      + team_id  = "3115450"
      + username = "leylmordor"
    }

Plan: 2 to add, 0 to change, 0 to destroy.

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d github/modules/organization/members`
* :put_litter_in_its_place: To **delete** this plan click [here](http://atlantis-f795755b9-7rrvx:4141/lock?id=mindvalley%252Fauxiliary%252Fgithub%252Fmodules%252Forganization%252Fmembers%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d github/modules/organization/members`
</details>

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`

**Comment by naiduarvind** [comment]
atlantis apply

**Comment by sauron-droid** [comment]
Ran Apply for dir: `github/modules/organization/members` workspace: `default`

**Apply Failed**: Pull request must be approved before running apply.

**Comment by naiduarvind** [comment]
atlantis apply

**Comment by sauron-droid** [comment]
Ran Apply for dir: `github/modules/organization/members` workspace: `default`

<details><summary>Show Output</summary>

```diff
module.leylmordor.github_membership.organization-membership: Creating...
module.leylmordor.github_team_membership.team-membership: Creating...
module.leylmordor.github_team_membership.team-membership: Creation complete after 4s [id=3115450:leylmordor]
module.leylmordor.github_membership.organization-membership: Creation complete after 5s [id=mindvalley:leylmordor]

Apply complete! Resources: 2 added, 0 changed, 0 destroyed.

The state of your infrastructure has been saved to the path
below. This state is required to modify and destroy your
infrastructure, so keep it safe. To inspect the complete state
use the `terraform show` command.

State path: terraform.tfstate

```
</details>

**Comment by sauron-droid** [comment]
Automatically merging because all plans have been successfully applied.

**Comment by sauron-droid** [comment]
Locks and plans deleted for the projects and workspaces modified in this pull request:

- dir: `github/modules/organization/members` workspace: `default`

**Pull request merged**
